name: CI

on:
  push:
    branches:
      - master # 触发工作流的分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build --file Dockerfile -t howxchove/nginx-webdav:${{ github.sha }} .
          docker tag howxchove/nginx-webdav:${{ github.sha }} howxcheng/nginx-webdav:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push howxcheng/nginx-webdav:latest
          docker push howxcheng/nginx-webdav:${{ github.sha }}
